spring:
  application:
    name: tanzu-java-web-app
management:
  endpoints:
    web:
      base-path: "/joel-actuator"
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

firstName: Larry

logging:
  level:
    root: DEBUG
