apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: joels-api-provider
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: joels-api-provider
    app.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    openapi-spec-endpoint: "/v3/api-docs"
spec:
  source:
    git:
      url: https://github.com/jrshaffe/tanzu-java-web-app
      ref:
        branch: main
